/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/approvals` | `/approvals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/expenses/new` | `/expenses/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sales/new` | `/sales/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/workers` | `/workers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/approvals` | `/approvals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/expenses` | `/expenses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/expenses/new` | `/expenses/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/sales` | `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/sales/new` | `/sales/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/workers` | `/workers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/approvals${`?${string}` | `#${string}` | ''}` | `/approvals${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/customers${`?${string}` | `#${string}` | ''}` | `/customers${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/expenses${`?${string}` | `#${string}` | ''}` | `/expenses${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/expenses/new${`?${string}` | `#${string}` | ''}` | `/expenses/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/sales${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/sales/new${`?${string}` | `#${string}` | ''}` | `/sales/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/workers${`?${string}` | `#${string}` | ''}` | `/workers${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/approvals` | `/approvals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/expenses/new` | `/expenses/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sales/new` | `/sales/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/workers` | `/workers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
